In [19]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv('/home/anuradha/Documents/anu/phd_project/TA-SYSTEMS/TA_systems_clean/set1/raw_files/hits.csv')
df.head()

,Strain,1H-CbtA_toxin,2H-Cpta_toxin,3H-Polyketide_cyc2,4H-Fic,5H-GNAT_acetyltran,6H-GNAT_acetyltran,7H-GnsAB_toxin,8H-Toxin_YhaV,9H-YdaT_toxin,...,160H-Zeta_toxin,161H-CbtA_toxin,162H-Couple_hipA,163H-ANT,164H-Zeta_toxin,165H-HipA_C,166H-Gp49,167H-DUF4258,168H-PIN,169H-PemK_toxin
0,ST001670050,2,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,ST006480109,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,ST000730234,2,1,1,1,1,1,1,1,3,...,0,0,0,0,0,0,0,0,0,0
3,ST000580141,0,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,ST000380050,2,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [21]:
df = df.drop(['Strain'], axis = 1)
df.head()

,1H-CbtA_toxin,2H-Cpta_toxin,3H-Polyketide_cyc2,4H-Fic,5H-GNAT_acetyltran,6H-GNAT_acetyltran,7H-GnsAB_toxin,8H-Toxin_YhaV,9H-YdaT_toxin,10H-HipA_C-Couple_hipA,...,160H-Zeta_toxin,161H-CbtA_toxin,162H-Couple_hipA,163H-ANT,164H-Zeta_toxin,165H-HipA_C,166H-Gp49,167H-DUF4258,168H-PIN,169H-PemK_toxin
0,2,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2,1,1,1,1,1,1,1,3,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,1,1,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df = df.T
df = df.reset_index()
df = df[['index']]
df.head()

                index
0       1H-CbtA_toxin
1       2H-Cpta_toxin
2  3H-Polyketide_cyc2
3              4H-Fic
4  5H-GNAT_acetyltran

In [23]:
# Create a new column with values before the hyphen
df['Hit Id'] = df['index'].str.split('-').str.get(0)

In [24]:
df.rename({'index': 'short_name'}, axis = 1, inplace = True)

In [25]:
df['Hit Id'] = df['Hit Id'].str.strip()

In [26]:
df.head()

           short_name Hit Id
0       1H-CbtA_toxin     1H
1       2H-Cpta_toxin     2H
2  3H-Polyketide_cyc2     3H
3              4H-Fic     4H
4  5H-GNAT_acetyltran     5H

In [27]:
df.to_csv('hits_pfam_annot_sorted.csv', index = False)